[package]
name = "gitrelease"
version = "0.1.2"
edition = "2021"
authors = ["Waldir Borba Junior <wborbajr@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
